version: "3"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3XSDc48PCgdQ2avV
      MYSQL_DATABASE: truenorth
      MYSQL_PASSWORD: nVBB5RdjfbjfnLDJ
      MYSQL_USER: truenorth
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./backend/database/1-schema.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: truenorthtestback
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/src/app/
    command: npm run dev:watch
    restart: on-failure
    ports:
      - "127.0.0.1:4000:8081"
    depends_on:
      - mysqldb
  frontend:
    container_name: truenorthtestfront
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes: 
      - ./frontend:/app
    ports:
      - "3001:3000"
    links:
      - "backend:be"
    depends_on:
      - backend