version: "3"
services:
  backend:
    container_name: truenorthtestback
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/src/app/
    command: npm run dev:watch
    restart: always
    ports:
      - "127.0.0.1:4000:8081"
  frontend:
    container_name: truenorthtestfront
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes: 
      - ./frontend:/app
    ports:
      - "3001:3000"
    links:
      - "backend:be"